import './globals.css'
import { Inter } from 'next/font/google'
import SideNav from '@/components/SideNav'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex home-screen h-screen w-screen bg-[#000A1F]`}>
      <SideNav/>
        {children}
        </body>
    </html>
  )
}
